x<-TRUE
print(class(x))
x<-67.54
print(class(x))
x<-50L
print(class(x))
x<-6+4i
print(class(x))
x<-"hello"
print(class(x))
typeof(5)
typeof("5")
a<-c(TRUE,TRUE,FALSE,0,6,7)
b<-c(FALSE,TRUE,FALSE,TRUE,TRUE,TRUE)
a&b #element wise
a&&b
a|b
a||b
!a
!b
x<-c(1,2,3,4,5)
x
l<-c(TRUE,FALSE)
l<-c(T,F)
c<-c("a","b","c","d")
i<-1:20
cm<-c(2+2i,3+3i)
print(l)
print(c)
print(i)
print(cm)
typeof(x)
typeof(l)
typeof(c)
typeof(i)
typeof(cm)
seq(1:20)
seq(1,20,length.out=5)
seq(1,20,by=2)
seq(1,20,length.out=6)
seq(from=1,to=10)
seq(from=1,to=10,by=2)
dataframe1<-data.frame(Name=c("Juan","Alcaraz","Simantha"),Age=c(22,15,19),Vote=c(TRUE,FALSE,TRUE))
print(dataframe1)
data_frame=data.frame(Training=c("STRENGTH","STAMINA","OTHER"),Pulse=c(120,110,150))
summary(data_frame)
df1<-data.frame(Name=c("Juan","Alcaraz"),Age=c(22,15))
df2<-data.frame(Name=c("Yiruma","Bach"),Age=c(46,89))
updated<-rbind(df1,df2)
print(updated)
mdf1<-data.frame(Name=c("Juan","Alcaraz"),Age=c(22,15))
mdf2<-data.frame(Hobby=c("Tennis","Piano"))
updated2<-cbind(mdf1,mdf2)
print(updated2)
dataframe1<-data.frame(Name=c("Juan","Alcaraz","Simantha"),Age=c(22,15,19),Vote=c(TRUE,FALSE,TRUE))
cat("Total Elements",length(dataframe1))
My_Data_Frame<-data.frame(Height=c("Tall","Average","Short"),Body_structure=c("Meso","Endo","Ecto"),Age=c(35,30,25))
My_Data_Frame[1]
My_Data_Frame[2]
My_Data_Frame[["Height"]]
My_Data_Frame$Height
celebrities=data.frame(name=c("Andrew","Mathew","Dany","Philip","John","Bing","Monica"),age=c(28,23,49,29,38,23,29),income=c(25.2,10.5,11,21.9,44,11.5,45))
extractedDF=data.frame(celebrities$age,celebrities$income)
print("New data frame two columns extracted from celibrities dataframe:")
print(extractedDF)
new_data=data.frame(name=c("Gary","Lee","Scofield"),age=c(29,22,33),income=c(21,5,31))
celebrities=rbind(celebrities,new_data)
print("Resulting dataframe after adding new rows:")
print(celebrities)